manager/urls.py
# coding=utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('manager.views',
    url(r'^$', 'manage', name='manage'),                # M
    url(r'^add/$', 'addBlog', name='add'),                  # A
    url(r'^upload/$', 'uploadBlog', name='uploadBlog'),                  # A
    url(r'^add_type/$', 'addType', name='add_type'),            # T
    url(r'^user/pwd/$', 'changePwd', name='changePwd'),             #PWD
    url(r'^blog/del/$', 'delBlog', name='delBlog'),                 # Delblog

    url(r'^pic/create_type/$', 'CreatePicType', name='CreatePicType'),  # create type
    url(r'^pic/upload_my_pic/(?P<id>\d+)/$', 'UploadMyPic', name='UploadMyPic'),  # up mypic
    url(r'^pic/upload/$', 'UploadPic', name='UploadPic'),  # upload
    url(r'^pic/edit_mypic/$', 'edit_mypic', name='edit_mypic'), # pic edit
)

mysite/urls.py
# coding=utf-8
from django.conf.urls import patterns, include, url
from django.views.decorators.cache import cache_page

from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'mysite.views.home', name='home'),                   # 首页
    url(r'^about/$', 'mysite.views.about', name='about'), 
    url(r'^docs/$', 'mysite.views.docs', name='docs'),                  # docs
    url(r'^resume/$', 'mysite.views.resume', name='resume'),                   # contact
    url(r'^manage/', include('manager.urls')),                      # manager
)

# Serve static files for admin, use this for debug usage only
# `python manage.py collectstatic` is preferred.
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from common.rss import LatestEntriesFeed
urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns('',
   (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
)


urlpatterns += patterns('mysite.views',
    url(r'^login/$', 'login_', name='login'),                           # 登陆
    url(r'^logout/$', 'logout_', name='logout'),                        # 登出
    url(r'^blog/(?P<id>\d+)/$', 'blog', name='blog'),                        # 正文
    url(r'^blog/search/$', 'search', name='search'),                    # 检索
    url(r'^blog/common/$', 'sidebar', name='sidebar'),                  # 侧栏异步加载
    url(r'^blog/type/(?P<id>\d+)/$', 'blogType', name='blogType'),      # 博客类型检索
    url(r'^blog/tag/(?P<id>\d+)/$', 'blogTag', name='blogTag'),         # 博客标签检索


    url(r'^wiki/$', 'wiki', name='wiki'),                               # 维基百科
    url(r'^wiki/(?P<id>\d+)/$', 'wiki', name='wiki'),                               # 维基百科
    url(r'^wiki/add_type/$', 'wiki_add_type', name='wiki_add_type'),    # 维基百科添加分类
    url(r'^wiki/add/(?P<id>\d+)/$', 'wiki_add', name='wiki_add'),    # 维基百科添加
    url(r'^common/del/$', 'commonDel', name='commonDel'),               # del

    url(r'^pic/$', 'pic', name='pic'),          # 图片首页
    url(r'^pic/(?P<id>\d+)/$', 'picView', name='picView'),          # 图片
    url(r'^feed/$', LatestEntriesFeed()),
    url(r'^pigeonhole/$', 'pigeonhole', name='pigeonhole'),          # 归档
    url(r'^ciphertext/(?P<id>\d+)/$', 'ciphertext', name='ciphertext'),          # 密文

)

#接口数据
urlpatterns += patterns('mysite.views',
    url(r'^api/category/$', 'getCategory', name='getCategory'),         # 获取分类
    url(r'^api/tag/$', 'getTag', name='getTag'),                        # 获取标签
)


#english
urlpatterns += patterns('mysite.english',
    url(r'^english/$', 'learnEnglish', name='learnEnglish'),         # english index
    url(r'^english/word/$', 'words', name='words'),         # english index
    url(r'^english/add_edit_words/(?P<type>\d+)/(?P<id>\d+)/', 'add_edit_words', name='add_edit_words'),
    url(r'^english/ok/', 'done', name='done'),
    url(r'^english/has_done/', 'has_done', name='has_done'),
)

if settings.DEBUG == False:
    handler500 = 'mysite.views.cus_500_err'
    handler404 = 'mysite.views.cus_404_err'

mysite/models.py
#coding=utf-8
from django.db import models
from wmd import models as wmd_models        # 导入wmd的models
from django.utils.encoding import force_unicode
from django.utils.safestring import mark_safe
import markdown


class Type(models.Model):
    """分类"""
    name = models.CharField(max_length=50)
    add_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name
    def getCount(self):
        """获取数目"""
        return Blog.objects.filter(type=self.id).count()

    class Meta:
        db_table = 'type'


        

class Blog(models.Model):
    title = models.CharField(max_length=100)
    type = models.IntegerField(default=0)
    img = models.CharField(max_length=500, null=True) # 博客导图
    summary = models.CharField(max_length=500, null=True)
    rss = models.CharField(max_length=1024, null=True)  # 订阅源
    content = wmd_models.MarkDownField()
    content_show = wmd_models.MarkDownField(u'正文显示', null=True)
    add_date = models.DateTimeField()
    counts = models.IntegerField(default=0)     # 点击率
    is_show = models.CharField(max_length=100, null=True)        # 加密
    def __unicode__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None):
        self.content_show = mark_safe(markdown.markdown(force_unicode(self.content), ['codehilite'], safe_mode='escape'))
        super(Blog, self).save()

    class Meta:
        db_table = 'blog'


    def getType(self):
        """获取类型"""
        return Type.objects.get(pk=self.type)

    def getTags(self):
        """获取标签"""
        return BlogTag.objects.filter(blog=self.id)





class Tag(models.Model):
    """个人标签"""
    name = models.CharField(max_length=100)
    add_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'tags'



class BlogTag(models.Model):
    """主题标签"""
    blog = models.ForeignKey(Blog)
    tag = models.ForeignKey(Tag)
    add_time = models.DateTimeField(auto_now=True)
    def __unicode__(self):
        return self.tag.name
    class Meta:
        db_table = 'blog_tag'



class WikiType(models.Model):
    """wiki分类"""
    name = models.CharField(max_length=50)
    add_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.name
    def getCount(self):
        """获取数目"""
        return Wiki.objects.filter(category=self.id).count()

    class Meta:
        db_table = 'wiki_type'


class Wiki(models.Model):
    """WIki"""
    category = models.IntegerField()
    content = wmd_models.MarkDownField()
    content_show = wmd_models.MarkDownField(u'show', null=True)
    add_time = models.DateTimeField(auto_now=True, auto_now_add=True)

    class Meta:
        db_table = 'wiki'

    def save(self, force_insert=False, force_update=False, using=None):
        self.content_show = mark_safe(markdown.markdown(force_unicode(self.content), ['codehilite'], safe_mode='escape'))
        super(Wiki, self).save()


class PicType(models.Model):
    """the picture categories"""
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=500, null=True)
    add_time = models.DateTimeField(auto_now=True)
    img = models.IntegerField(null=True)    # id for pic
    def getPicCount(self):
        return MyPic.objects.filter(type=self.id).count()
    def getPic(self):
        return Pic.objects.get(pk=self.img)
    class Meta:
        db_table = 'pic_type'


class Pic(models.Model):
    """picture"""
    img = models.CharField(max_length=200)
    key = models.CharField(max_length=200)  # qiniu key
    add_time = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'pic'


class MyPic(models.Model):
    """my picture"""
    type = models.IntegerField()
    img = models.IntegerField(null=True)        # id for pic
    desc = models.CharField(max_length=500, null=True)
    add_date = models.DateTimeField(auto_now=True, auto_now_add=True)
    def getType(self):
        return PicType.objects.get(pk=self.type)
    def getPic(self):
        return Pic.objects.get(pk=self.img)
    class Meta:
        db_table = 'mypic'


class Word(models.Model):
    status = models.IntegerField(default=0) # 0:None; 1:Ok
    add_date = models.DateField(auto_now=True)

    class Meta:
        db_table = 'word'


class Words(models.Model):
    word = models.ForeignKey(Word)
    english = models.CharField(max_length=100)              # 0:None; 1:Ok
    explain = models.CharField(max_length=300, null=True)
    phonetic = models.CharField(max_length=100, null=True)   #  英标
    seq = models.CharField(max_length=300, null=True)
    add_time = models.DateTimeField(auto_now=True)
    status = models.IntegerField(default=0)   # ok

    class Meta:
        db_table = 'words'

manager/views.py
# coding=utf-8
from django.shortcuts import render
from common.form import BlogForm,PasswordForm, PicTypeForm, MypicForm
from django.http import HttpResponseRedirect, HttpResponse
from mysite.models import Type, Tag, Blog, BlogTag, PicType, Pic, MyPic
from django.shortcuts import get_object_or_404
from common import ajax
import simplejson as json
import datetime
import random
import re, string
from common.superqiniu import SuperQiniu
from BeautifulSoup import BeautifulSoup
from markdown import markdown


def manage(request):
    """后台"""
    context = {}
    user = request.user

    return render(request, 'manager/manage.html', context)




def addBlog(request):
    """add blog"""
    context = {}
    now = datetime.datetime.now()
    user = request.user
    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            formData = form.cleaned_data
            title = formData.get('title')
            pwd = formData.get('is_show', '')
            content = formData.get('content')
            type = formData.get('type')
            tags = request.POST.get('id_tag', '')
            obj = int(request.POST.get('edit_or_creat', 0))    # 编辑还是创建
            now = datetime.datetime.now()

            # 保存theme
            # 将markdown格式转换纯文本

            from markdown import markdown
            html = markdown(content)
            rss = ''.join(BeautifulSoup(html).findAll(text=True))  # rss订阅源
            if len(content) > 500:
                html = markdown(content[:500])
            summary = ''.join(BeautifulSoup(html).findAll(text=True))

            if obj:     # 编辑状态
                blog = Blog.objects.filter(id=obj).update(title=title, type=int(type), summary=summary,rss=rss, content=content, add_date=now, is_show=pwd)
                blog = Blog.objects.get(id=obj)
            else:
                blog = Blog.objects.create(
                    title=title, type=int(type), summary=summary, rss=rss, content=content, add_date=now, is_show=pwd
                )
            # 博客导图
            img = getPic(blog.content_show)
            blog.img = img
            blog.save()

            if tags:
                tags = json.loads(tags)
                tag_list = []
                for i in tags:
                    i = i.strip()
                    if i and not Tag.objects.filter(name__iexact=i).exists():
                        tag = Tag.objects.create(name=i)
                        tag_list.append(tag)
                    elif i:
                        tag_list.append(Tag.objects.filter(name__iexact=i)[0])

                if obj:     # 编辑状态
                    BlogTag.objects.filter(blog=blog).delete()
                # 创建ThemeTag
                for i in tag_list:
                    BlogTag.objects.create(blog=blog, tag=i)

            return HttpResponseRedirect('/')

        context['form'] = form
        return render(request, 'manager/addtheme.html', context)
    else:
        id = request.GET.get('id', None)
        context['form'] = BlogForm()
        is_edit = 0
        if id:      # 编辑状况
            is_edit = id
            blog = get_object_or_404(Blog, pk=int(id))
            context['form'] = BlogForm(instance=blog)
            context['has_tags'] = BlogTag.objects.filter(blog=blog)
        codes = Type.objects.all().order_by('-id')
        tags = Tag.objects.all().order_by('-id')
        context['codes'] = codes
        context['tags'] = tags
        context['is_edit'] = is_edit
    return render(request, 'manager/addtheme.html', context)



def uploadBlog(request):
    """Upload blog"""
    context = {}
    now = datetime.datetime.now()
    if request.method == 'POST':
        type = request.POST.get('type')
        tags = request.POST.get('id_tag', '')
        file = request.FILES.get('blog')
        context = file.read().decode('utf-8').split('---', 2)
        content = [i for i in context if i]
        head = content[0]
        body = content[1]
        title =  re.findall(r'title: .*', head)
        if title:
            title = title[0].split(':')[1].strip()
        else:
            title = u'一个神秘的标题'

        html = markdown(body)
        rss = ''.join(BeautifulSoup(html).findAll(text=True))  # rss订阅源
        if len(body) > 500:
            html = markdown(body[:500])

        summary = ''.join(BeautifulSoup(html).findAll(text=True))
        blog = Blog.objects.create(
                    title=title, type=int(type), summary=summary,rss=rss, content=body, add_date=now
                )
        # 博客导图
        img = getPic(blog.content_show)
        blog.img = img
        blog.save()
        if tags:
            tags = json.loads(tags)
            tag_list = []
            for i in tags:
                i = i.strip()
                if i and not Tag.objects.filter(name__iexact=i).exists():
                    tag = Tag.objects.create(name=i)
                    tag_list.append(tag)
                elif i:
                    tag_list.append(Tag.objects.filter(name__iexact=i)[0])

            # 创建ThemeTag
            for i in tag_list:
                BlogTag.objects.create(blog=blog, tag=i)
        return HttpResponseRedirect('/')
    context['types'] = Type.objects.order_by('-id')
    context['tags'] = Tag.objects.order_by('-id')
    return render(request, 'manager/uploadblog.html', context)


def addType(request):
    """添加分类"""
    user = request.user
    if request.method == 'POST':
        name = request.POST.get('name').strip().lower()
        if not Type.objects.filter(name__iexact=name).exists():
            c_id = Type.objects.create(name=name).id
            return ajax.ajax_ok(c_id)



def changePwd(request):
    """更改密码"""
    context = {}
    user = request.user
    context['form'] = PasswordForm()
    if request.method == 'POST':
        form = PasswordForm(user, request.POST)
        if form.is_valid():
            newpwd = form.cleaned_data.get('password1', None)
            if newpwd:
                user.set_password(newpwd)
                user.save()
                return HttpResponseRedirect('/')
        context['form'] = form
    return render(request, 'manager/pwd.html', context)


def getPic(html):
    """获取图片"""
    soup = BeautifulSoup(html)
    s = soup.find('img')
    if s:
        return s['src']
    return '/site_media/img/blog/%s.jpg' % (random.choice(range(1, 10)))


def delBlog(request):
    """del blog"""
    if request.method == 'POST':
        id = request.POST.get('id')
        BlogTag.objects.filter(blog__id=id).delete()
        Blog.objects.filter(id=id).delete()
        return HttpResponse('ok')




def UploadPic(request):
    """upload pic to qiniu."""
    if request.method == 'POST':
        img = request.FILES.get('Filedata', None)
        type = request.POST.get('type', None)
        if type:
            qn = SuperQiniu(img, w=800, h=520)
        else:
            qn = SuperQiniu(img)
        qn.uploadFile()
        remote_url = qn.downloadFile()
        key = qn.getKey()
        pic = Pic.objects.create(img=remote_url, key=key)
        return ajax.ajax_ok({'id':pic.id, 'url':pic.img, 'key':key})



def CreatePicType(request):
    """create the type of picture"""
    context = {}
    if request.method == 'POST':
        id = int(request.POST.get('id', 0))
        if id:
            pictype =get_object_or_404(PicType, pk=id)
            form = PicTypeForm(request.POST, instance=pictype)
        else:
            form = PicTypeForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            img = request.POST.get('pid')
            f.img = img
            f.save()
            return HttpResponseRedirect('/pic/')
        context['form'] = form

    else:
        id = request.GET.get('id', None)
        form = PicTypeForm()
        if id:
            pictype =get_object_or_404(PicType, pk=id)
            context['img_obj'] = pictype.getPic()
            form = PicTypeForm(instance=pictype)
        context['form'] = form
        context['id'] = id

    return render(request, 'pic/addtype.html', context)


def UploadMyPic(request, id):
    """create the type of picture"""
    context = {}
    if request.method == 'POST':
        data = request.POST.get('data')
        data = json.loads(data)

        for obj in data:
            MyPic.objects.create(type=id, img=obj['pid'], desc=obj['desc'])
        return HttpResponse('ok')

    else:
        pictype =get_object_or_404(PicType, pk=id)
        context['pictype'] = pictype

    return render(request, 'pic/addpic.html', context)



def edit_mypic(request):
    """edit mypic"""
    if request.method == 'POST':
        id = request.POST.get('id')
        desc = request.POST.get('desc', '')
        MyPic.objects.filter(pk=id).update(desc=desc)
        return HttpResponse('ok')

mysite/templates/manager/addtheme.html
{% extends 'base.html' %}
{% load markup %}
{% block css %}
    <link href="/site_media/bootstrap-tagsinput/bootstrap-tagsinput.css" rel="stylesheet">
    <link href="/site_media/css/pygments-css-master/emacs.css/" rel="stylesheet">
    <link href="/site_media/wmd/wmd.css/" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="row">
        <form class="form-signin2" role="form" id="themeform" action="/manage/add/" method="post">
         {% csrf_token %}
            <h2 class="form-signin-heading">发布博客</h2>
            <p><b>标题：</b></p>
            {{ form.title }}
            <p><b>类型：</b></p>
            {{ form.type }}
            <div class="btn-group" id="codes">
               {% for obj in codes %}
                <button type="button" class="btn btn-default" style="margin-right: 10px;display: block" id="c_{{ obj.id }}">{{ obj.name }}</button>
               {% endfor %}
               <input type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#addType" style="margin-right: 10px;display: block" id="adds" value="添加分类">
            </div>
            <p><b>加密：</b></p>
            {{ form.is_show }}
            <p></p>

            <div class="panel panel-default">
                  <div class="panel-heading"><b>内容：</b></div>
                  <div class="panel-body">
                    {{ form.content }}
                  </div>
            </div>
              <!--预览-->
              <div class="panel panel-default" id="prew_box">
                  <div class="panel-heading">内容即时预览</div>
                  <div class="panel-body">
                    <div id="prew_c"></div>
                  </div>
              </div>

            <p><b>添加标签：</b></p>
            <div>
                <input type="text" id="yourtags" data-role="tagsinput" placeholder="添加标签" />

            </div>
            {% if has_tags %}
                 <p id="has_tags" style="display: none">已存在的标签：{% for obj in has_tags %}<span class="label label-primary" onclick="addIt('{{ obj.tag.name }}')">{{ obj.tag.name }}</span>{% endfor %}
            {% endif %}
            {% if tags %}<p id="tags_">已存在的标签：{% for obj in tags %}<span class="label label-primary" onclick="addIt('{{ obj.name }}')">{{ obj.name }}</span>&nbsp;{% endfor %}</p>{% endif %}
            <input type="hidden" name="id_tag" value=""/>
            <input type="hidden" name="edit_or_creat" value="{{ is_edit }}" />
            <a href="javascript:;" id="submit" class="btn btn-lg btn-primary btn-block"  data-loading-text="正在加载...">发　布</a>
        </form>
  </div>
    <br/>  <br/>


<!-- Modal 添加标签 -->
<div class="modal fade" id="addType" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">添加标签:</h4>
      </div>
      <div id="s_ms_box">
      <div class="modal-body">
        <form role="form">
          <div class="form-group">
            <label for="msTitle">名称</label>
            <p class="small" style="color: #c04b4b; font-weight: bold; display: none" id="ms_title">*标题必填</p>
            <input type="type" class="form-control" id="msTitle" placeholder="名称">
          </div>

        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-info" onclick="addType()">添加</button>
      </div>
      </div>

      <div id="sendok" style="display: none">
          <div class="modal-body">
          <p id="tips">添加成功</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock %}
{% block js %}
    <script src="/site_media/js/main.js"></script>
    <script src="/site_media/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
    <script src="/site_media/wmd/wmd.js"></script>
    <script src="/site_media/wmd/showdown.js"></script>
    <script>
    var IS_EDIT = location.href.split('=').length;
    $(function(){
        $('#prew_c').append($('.wmd-panel:last'));
        $('#id_type').hide();
        if(IS_EDIT == 2){ // 编辑状态
            var type = $('#id_type').val();
            $('#c_'+type).addClass('btn btn-success');
            $('#has_tags').children('span').each(function(){
                $(this).bind('click', addIt($(this).text()))
            })
        }
    })
    </script>
{% endblock %}

mysite/templates/manager/manage.html
{% extends 'base.html' %}
{% load mytags %}
{% block content %}
{% endblock %}

mysite/templates/manager/pwd.html
{% extends 'base.html' %}
{% block content %}
<form class="form-signin" role="form" action="/manage/user/pwd/" method='post'>{% csrf_token %}
        <h2 class="form-signin-heading">修改密码</h2>
        {{ form.as_p }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">保 存</button>
      </form>
{% endblock %}

mysite/templates/manager/uploadblog.html
{% extends 'base.html' %}
{% load markup %}
{% block css %}
    <link href="/site_media/bootstrap-tagsinput/bootstrap-tagsinput.css" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="row">
<form enctype="multipart/form-data" method="post" action="{{ request.path }}" id="uploadform">
            <h2 class="form-signin-heading">上传文档</h2>
            <div class="form-group">
                <label for="exampleInputFile">上传文档</label>
                <input type="file" id="blog" name="blog">
                <p class="help-block">只能处理.md格式的文档.</p>
             </div>
            <p><b>类型：</b></p>
            <div class="btn-group" id="codes">
               {% for obj in types %}
                <button type="button" class="btn btn-default" style="margin-right: 10px;display: block" id="c_{{ obj.id }}">{{ obj.name }}</button>
               {% endfor %}
               <input type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#addType" style="margin-right: 10px;display: block" id="adds" value="添加分类">
            </div>
            <p></p>

            <p><b>添加标签：</b></p>
            <div>
                <input type="text" id="yourtags" data-role="tagsinput" placeholder="添加标签" />
            </div>
            {% if has_tags %}
                 <p id="has_tags" style="display: none">已存在的标签：{% for obj in has_tags %}<span class="label label-primary" onclick="addIt('{{ obj.tag.name }}')">{{ obj.tag.name }}</span>{% endfor %}
            {% endif %}
            {% if tags %}<p id="tags_">已存在的标签：{% for obj in tags %}<span style="margin-bottom: 8px;" class="label label-primary" onclick="addIt('{{ obj.name }}')">{{ obj.name }}</span>&nbsp;{% endfor %}</p>{% endif %}
            <a href="javascript:;" id="upload" class="btn btn-lg btn-primary btn-block"  data-loading-text="正在加载...">发　布</a>
            <!--隐藏域-->
            <input type="hidden" name="id_tag"/>
            <input type="hidden" name="type"/>
  </form>
</div>
    <br/>


<!-- Modal 添加标签 -->
<div class="modal fade" id="addType" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">添加标签:</h4>
      </div>
      <div id="s_ms_box">
      <div class="modal-body">
        <form role="form">
          <div class="form-group">
            <label for="msTitle">名称</label>
            <p class="small" style="color: #c04b4b; font-weight: bold; display: none" id="ms_title">*标题必填</p>
            <input type="type" class="form-control" id="msTitle" placeholder="名称">
          </div>

        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
        <button type="button" class="btn btn-info" onclick="addType()">添加</button>
      </div>
      </div>

      <div id="sendok" style="display: none">
          <div class="modal-body">
          <p id="tips">添加成功</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
          </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock %}
{% block js %}
    <script src="/site_media/js/main.js"></script>
    <script src="/site_media/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
    <script>
    $(function(){

    })
    </script>
{% endblock %}